"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express = require("express");
const router = express.Router();
const users_controllers_1 = require("../controllers/users.controllers");
router.get('/', users_controllers_1.getRequest);
router.post('/', users_controllers_1.postRequest);
router.put('/', users_controllers_1.putRequest);
router.delete('/', users_controllers_1.deleteRequest);
exports.default = router;
